#!/usr/bin/env perl

use strict;
use warnings;
use Cwd;

# Example config: URxvt.keysym.Control-Shift-N: perl:new-window

sub new_window
{
    my ($self) = @_;
    my $ccwd = readlink("/proc/".$self->{child_pid}."/cwd");
    new urxvt::term $self->env, $urxvt::RXVTNAME, -cd => $ccwd;
}

sub on_child_start {
    my ($self,$pid) = @_;

    $self->{child_pid} = $pid;
    ()
}


sub on_user_command
{
    my ($self, $cmd) = @_;

    if ($cmd eq "new-window") {
        new_window($self);
    }
}

